model_path: 
   base_model: /cpfs01/shared/NLP-A100/NLP-A100_hdd/feyuan/model/non_llama_family/mpt-7b
   lora: null
   torch_dtype: fp16

dataset:
   loader: flores
   path: /cpfs01/shared/NLP-A100/NLP-A100_hdd/jie/benchmark/flores-101/devtest/
   input_file: eng.devtest
   inst_file: /cpfs01/shared/NLP-A100/NLP-A100_hdd/jie/multilingual_LLM/prepare/instruct_inf.txt
   lang_instruction: /cpfs01/shared/NLP-A100/NLP-A100_hdd/jie/multilingual_LLM/prepare/language_name_code_pair.xlsx
   input_extra_file: null
   lang_pair: en-zh
   inst_placeholder: null
   inst_fix: true
   inst_index: 0
   labels: null
   inst_with_input: true 
   input_size: -1
   use_match: false

generat:
    beam_size: 4
    temperature: 0.1
    batch_size: 8
    template: prompt_input # 
    search: beam 
    do_sample: false
    
output:
    subpath: ""
    output_file_prefix: generation_results
 
